### ISSUE TITLE
Persistent/shell mode for exec

### ISSUE THREAD

**Issue by ssmirr** [ottomatica/infra.connectors#4]
Add an option in `exec()` to run commands in "persistent" mode. That means if you run `exec('cd /root')`, and then run `exec('ls')`, `ls` command should already be in `/root`. Similarly env variables that are set should be accessible in next `exec()` calls.

**Comment by chrisparnin** [comment]
Some interesting options for helping collect exit codes, plus stderr/stdout from commands.

Works in ash/bash
```
ssh -i /Users/cjparnin/.slim/baker_rsa root@192.168.64.53 -p 22 -o StrictHostKeyChecking=no "
sig_handler() {
echo "E: failed with exitcode \$?" 1>&2
}

trap sig_handler EXIT
exit 10
```

https://stackoverflow.com/questions/637827/redirect-stderr-and-stdout-in-bash
https://stackoverflow.com/questions/29876345/send-stderr-stdout-messages-to-function-and-trap-exit-signal

**Comment by ssmirr** [comment]
Closing old issue. `execPersistent()` was added in the commits above (79da41e).
